import { TaskProps } from "../types/task_types"

export let TasksData: TaskProps[] = [
    {
      title: "Complete React Native Project",
      description: "Finish implementing all screens and functionalities for the React Native mobile app.",
      day: "Monday",
      date: "2025-02-03",
      updateTime: "14:30",
      updateDate: "2025-02-02",
      noCharacters: 28,
    },
    {
      title: "Prepare UI/UX Design",
      description: "Create wireframes and prototypes for the upcoming web and mobile application.",
      day: "Tuesday",
      date: "2025-02-04",
      updateTime: "10:00",
      updateDate: "2025-02-03",
      noCharacters: 22,
    },
    {
      title: "Fix API Integration Issues",
      description: "Resolve authentication and data fetching issues in API endpoints.",
      day: "Wednesday",
      date: "2025-02-05",
      updateTime: "16:45",
      updateDate: "2025-02-04",
      noCharacters: 26,
    },
    {
      title: "Write Documentation",
      description: "Document the project structure, API routes, and setup instructions for developers.",
      day: "Thursday",
      date: "2025-02-06",
      updateTime: "12:15",
      updateDate: "2025-02-05",
      noCharacters: 19,
    },
    {
      title: "Deploy to Production",
      description: "Prepare the final build and deploy the project to the production server.Prepare the final build and deploy the project to the production server.Prepare the final build and deploy the project to the production server.Prepare the final build and deploy the project to the production server.Prepare the final build and deploy the project to the production server.",
      day: "Friday",
      date: "2025-02-07",
      updateTime: "18:00",
      updateDate: "2025-02-06",
      noCharacters: 21,
    },
    {
      title: "Deploy to Production",
      description: "Prepare the final build and deploy the project to the production server.Prepare the final build and deploy the project to the production server.Prepare the final build and deploy the project to the production server.Prepare the final build and deploy the project to the production server.Prepare the final build and deploy the project to the production server.",
      day: "Friday",
      date: "2025-02-07",
      updateTime: "18:00",
      updateDate: "2025-02-06",
      noCharacters: 21,
    },
    {
      title: "Deploy to Production",
      description: "Prepare the final build and deploy the project to the production server.Prepare the final build and deploy the project to the production server.Prepare the final build and deploy the project to the production server.Prepare the final build and deploy the project to the production server.Prepare the final build and deploy the project to the production server.",
      day: "Friday",
      date: "2025-02-07",
      updateTime: "18:00",
      updateDate: "2025-02-06",
      noCharacters: 21,
    },
    {
      title: "Deploy to Production",
      description: "Prepare the final build and deploy the project to the production server.Prepare the final build and deploy the project to the production server.Prepare the final build and deploy the project to the production server.Prepare the final build and deploy the project to the production server.Prepare the final build and deploy the project to the production server.",
      day: "Friday",
      date: "2025-02-07",
      updateTime: "18:00",
      updateDate: "2025-02-06",
      noCharacters: 21,
    },
  ];
  